// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcC_jiRpN_yWnGXFfzj7OCCnp73LdltGU',
    appId: '1:638037754928:web:e1cc5244ba8f036d7d99f5',
    messagingSenderId: '638037754928',
    projectId: 'academic-portal-48b66',
    authDomain: 'academic-portal-48b66.firebaseapp.com',
    storageBucket: 'academic-portal-48b66.firebasestorage.app',
    measurementId: 'G-KTWBFKZML0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qsq8q1PA0apH7uv2MnWnjh4qy9HIMRY',
    appId: '1:638037754928:android:8b7f344d0b0bc7ef7d99f5',
    messagingSenderId: '638037754928',
    projectId: 'academic-portal-48b66',
    storageBucket: 'academic-portal-48b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJLFVKS_97fRKcbPHkAp5PW-5sBIyM3c',
    appId: '1:638037754928:ios:a4db9f13f4a78c057d99f5',
    messagingSenderId: '638037754928',
    projectId: 'academic-portal-48b66',
    storageBucket: 'academic-portal-48b66.firebasestorage.app',
    iosBundleId: 'com.academicportal.academicPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcC_jiRpN_yWnGXFfzj7OCCnp73LdltGU',
    appId: '1:638037754928:web:91e42767624743437d99f5',
    messagingSenderId: '638037754928',
    projectId: 'academic-portal-48b66',
    authDomain: 'academic-portal-48b66.firebaseapp.com',
    storageBucket: 'academic-portal-48b66.firebasestorage.app',
    measurementId: 'G-7NW1NM20TZ',
  );
}
