// File generated by FlutterFire CLI placeholder / default options.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcademicPortalWebMockKey1234567890',
    appId: '1:123456789012:web:academicportalmockid01',
    messagingSenderId: '123456789012',
    projectId: 'academic-portal-platform',
    authDomain: 'academic-portal-platform.firebaseapp.com',
    storageBucket: 'academic-portal-platform.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcademicPortalAndroidMockKey123456',
    appId: '1:123456789012:android:academicportalandroid',
    messagingSenderId: '123456789012',
    projectId: 'academic-portal-platform',
    storageBucket: 'academic-portal-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcademicPortalIOSMockKey12345678901',
    appId: '1:123456789012:ios:academicportaliosapp001',
    messagingSenderId: '123456789012',
    projectId: 'academic-portal-platform',
    storageBucket: 'academic-portal-platform.appspot.com',
    iosBundleId: 'com.academicportal.academicPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcademicPortalIOSMockKey12345678901',
    appId: '1:123456789012:ios:academicportaliosapp001',
    messagingSenderId: '123456789012',
    projectId: 'academic-portal-platform',
    storageBucket: 'academic-portal-platform.appspot.com',
    iosBundleId: 'com.academicportal.academicPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcademicPortalWebMockKey1234567890',
    appId: '1:123456789012:web:academicportalmockid01',
    messagingSenderId: '123456789012',
    projectId: 'academic-portal-platform',
    authDomain: 'academic-portal-platform.firebaseapp.com',
    storageBucket: 'academic-portal-platform.appspot.com',
  );
}
